branches:
    only:
        - master

language: node_js
node_js:
    - node

notifications:
    email: false

sudo: required
dist: trusty

before_install:
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -extension RANDR"
