site_name: Argo
site_url: http://argo.js.org/
site_description: Argo is an open source trading platform, based on HTML5 technology, connecting directly with OANDA through the powerful API to develop trading strategies.
site_author: Alberto Santini
site_favicon: favicon.ico

repo_url: https://github.com/albertosantini/argo

theme: readthedocs
repo_name: GitHub
