name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: yarn install
      run: npm install

    - name: Upload Error Logs
      run: echo 'Uploading error logs'
      if: failure()
      uses: actions/upload-artifact@v1
      with:
        name: error-logs
        path: logs/
      run: npm test
      env:
        CI: true
